## Lectura del archivo csv con pandas

In [5]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
df = pd.read_csv("Measurement_summary.csv")
df

Latitude   Longitude    SO2    NO2     O3   CO  PM10  PM2.5  \
0       37.572016  127.005008  0.004  0.059  0.002  1.2    73     57   
1       37.572016  127.005008  0.004  0.058  0.002  1.2    71     59   
2       37.572016  127.005008  0.004  0.056  0.002  1.2    70     59   
3       37.572016  127.005008  0.004  0.056  0.002  1.2    70     58   
4       37.572016  127.005008  0.003  0.051  0.002  1.2    69     61   
...           ...         ...    ...    ...    ...  ...   ...    ...   
647506  37.544962  127.136792  0.003  0.028  0.013  0.5    23     17   
647507  37.544962  127.136792  0.003  0.025  0.015  0.4    25     19   
647508  37.544962  127.136792  0.003  0.023  0.015  0.4    24     17   
647509  37.544962  127.136792  0.003  0.040  0.004  0.5    25     18   
647510  37.544962  127.136792  0.003  0.037  0.005  0.5    27     18   

        Station Code  
0                101  
1                101  
2                101  
3                101  
4                101  
...              ...  
647506           125  
647507           125  
647508           125  
647509           125  
647510           125  

[647511 rows x 9 columns]

### Estandariza un conjunto de datos a lo largo de cualquier eje.

### Centro a la media y escala de componentes a la varianza de la unidad.

In [17]:
# Como se tiene valores no float64, se reemplaza los valores que son str por un dato numerico.

matriz = np.array(mat) 

matriz_salida_normalize = preprocessing.scale(matriz)
print('')
print(matriz_salida_normalize)


[[-1.66408345 -1.66408345 -1.66408345 ... -1.12744457  0.59912365
  -1.66408345]
 [-1.66408345 -1.66408345 -1.66408345 ... -1.0548742  -0.64834609
  -1.66408345]
 [-1.66408345 -1.66408345 -1.66408345 ... -0.98230384 -0.64834609
  -1.66408345]
 ...
 [ 1.6640222   1.6640222   1.6640222  ...  0.46910346  0.75505737
   1.6640222 ]
 [ 1.6640222   1.6640222   1.6640222  ...  3.08163658 -0.88224667
   1.6640222 ]
 [ 1.6640222   1.6640222   1.6640222  ...  0.39653309 -0.88224667
   1.6640222 ]]


### Escale los vectores de entrada individualmente a la normal unitaria

In [16]:
matriz = np.array(mat) 

matriz_salida_normalize = preprocessing.normalize(matriz)
print('Normalize')
print(matriz_salida_normalize)

Normalize
[[0.02750327 0.02750327 0.02750327 ... 0.02750327 0.68758166 0.02750327]
 [0.06008418 0.06008418 0.06008418 ... 0.12016835 0.54075759 0.06008418]
 [0.04540766 0.04540766 0.04540766 ... 0.13622298 0.40866895 0.04540766]
 ...
 [0.36005715 0.36005715 0.36005715 ... 0.33125258 0.38886173 0.36005715]
 [0.29940657 0.29940657 0.29940657 ... 0.70659949 0.07185758 0.29940657]
 [0.28209446 0.28209446 0.28209446 ... 0.24824313 0.06770267 0.28209446]]


### Agrupa los datos continuos en intervalos.

In [14]:
matriz = np.array(mat) 

matriz_salida_scale = preprocessing.KBinsDiscretizer(matriz)
print(matriz_salida_scale)

KBinsDiscretizer(n_bins=array([[1, 1, 1, ..., 1, 25, 1],
       [1, 1, 1, ..., 2, 9, 1],
       [1, 1, 1, ..., 3, 9, 1],
       ...,
       [25, 25, 25, ..., 23, 27, 25],
       [25, 25, 25, ..., 59, 6, 25],
       [25, 25, 25, ..., 22, 6, 25]], dtype=object))
